// Maps English country names (as stored in IndoorCO2MapData.json) to IANA timezone strings.
// For countries spanning multiple zones the most populous / representative timezone is used.
const COUNTRY_TIMEZONES = {
  // Europe
  'Germany':                  'Europe/Berlin',
  'Austria':                  'Europe/Vienna',
  'Switzerland':              'Europe/Zurich',
  'Liechtenstein':            'Europe/Vaduz',
  'France':                   'Europe/Paris',
  'Monaco':                   'Europe/Monaco',
  'Belgium':                  'Europe/Brussels',
  'Netherlands':              'Europe/Amsterdam',
  'Luxembourg':               'Europe/Luxembourg',
  'United Kingdom':           'Europe/London',
  'Ireland':                  'Europe/Dublin',
  'Spain':                    'Europe/Madrid',
  'Portugal':                 'Europe/Lisbon',
  'Italy':                    'Europe/Rome',
  'San Marino':               'Europe/San_Marino',
  'Vatican City':             'Europe/Vatican',
  'Malta':                    'Europe/Malta',
  'Greece':                   'Europe/Athens',
  'Cyprus':                   'Asia/Nicosia',
  'Sweden':                   'Europe/Stockholm',
  'Norway':                   'Europe/Oslo',
  'Denmark':                  'Europe/Copenhagen',
  'Finland':                  'Europe/Helsinki',
  'Iceland':                  'Atlantic/Reykjavik',
  'Estonia':                  'Europe/Tallinn',
  'Latvia':                   'Europe/Riga',
  'Lithuania':                'Europe/Vilnius',
  'Poland':                   'Europe/Warsaw',
  'Czech Republic':           'Europe/Prague',
  'Czechia':                  'Europe/Prague',
  'Slovakia':                 'Europe/Bratislava',
  'Hungary':                  'Europe/Budapest',
  'Slovenia':                 'Europe/Ljubljana',
  'Croatia':                  'Europe/Zagreb',
  'Bosnia and Herzegovina':   'Europe/Sarajevo',
  'Serbia':                   'Europe/Belgrade',
  'Montenegro':               'Europe/Podgorica',
  'North Macedonia':          'Europe/Skopje',
  'Albania':                  'Europe/Tirane',
  'Kosovo':                   'Europe/Belgrade',
  'Romania':                  'Europe/Bucharest',
  'Bulgaria':                 'Europe/Sofia',
  'Moldova':                  'Europe/Chisinau',
  'Ukraine':                  'Europe/Kyiv',
  'Belarus':                  'Europe/Minsk',
  'Russia':                   'Europe/Moscow',
  'Turkey':                   'Europe/Istanbul',
  'Georgia':                  'Asia/Tbilisi',
  'Armenia':                  'Asia/Yerevan',
  'Azerbaijan':               'Asia/Baku',
  'Andorra':                  'Europe/Andorra',

  // Americas
  'United States':                'America/New_York',
  'United States of America':     'America/New_York',
  'Canada':                       'America/Toronto',
  'Mexico':                       'America/Mexico_City',
  'Brazil':                       'America/Sao_Paulo',
  'Argentina':                    'America/Argentina/Buenos_Aires',
  'Chile':                        'America/Santiago',
  'Colombia':                     'America/Bogota',
  'Peru':                         'America/Lima',
  'Venezuela':                    'America/Caracas',
  'Ecuador':                      'America/Guayaquil',
  'Bolivia':                      'America/La_Paz',
  'Paraguay':                     'America/Asuncion',
  'Uruguay':                      'America/Montevideo',
  'Panama':                       'America/Panama',
  'Costa Rica':                   'America/Costa_Rica',
  'Guatemala':                    'America/Guatemala',
  'Honduras':                     'America/Tegucigalpa',
  'El Salvador':                  'America/El_Salvador',
  'Nicaragua':                    'America/Managua',
  'Cuba':                         'America/Havana',
  'Dominican Republic':           'America/Santo_Domingo',
  'Puerto Rico':                  'America/Puerto_Rico',
  'Jamaica':                      'America/Jamaica',
  'Trinidad and Tobago':          'America/Port_of_Spain',

  // Asia
  'Japan':                    'Asia/Tokyo',
  'China':                    'Asia/Shanghai',
  'South Korea':              'Asia/Seoul',
  'Republic of Korea':        'Asia/Seoul',
  'North Korea':              'Asia/Pyongyang',
  'Taiwan':                   'Asia/Taipei',
  'Hong Kong':                'Asia/Hong_Kong',
  'Macau':                    'Asia/Macau',
  'India':                    'Asia/Kolkata',
  'Pakistan':                 'Asia/Karachi',
  'Bangladesh':               'Asia/Dhaka',
  'Sri Lanka':                'Asia/Colombo',
  'Nepal':                    'Asia/Kathmandu',
  'Afghanistan':              'Asia/Kabul',
  'Iran':                     'Asia/Tehran',
  'Iraq':                     'Asia/Baghdad',
  'Saudi Arabia':             'Asia/Riyadh',
  'United Arab Emirates':     'Asia/Dubai',
  'UAE':                      'Asia/Dubai',
  'Qatar':                    'Asia/Qatar',
  'Kuwait':                   'Asia/Kuwait',
  'Bahrain':                  'Asia/Bahrain',
  'Oman':                     'Asia/Muscat',
  'Jordan':                   'Asia/Amman',
  'Lebanon':                  'Asia/Beirut',
  'Israel':                   'Asia/Jerusalem',
  'Palestine':                'Asia/Gaza',
  'Syria':                    'Asia/Damascus',
  'Yemen':                    'Asia/Aden',
  'Kazakhstan':               'Asia/Almaty',
  'Uzbekistan':               'Asia/Tashkent',
  'Kyrgyzstan':               'Asia/Bishkek',
  'Tajikistan':               'Asia/Dushanbe',
  'Turkmenistan':             'Asia/Ashgabat',
  'Mongolia':                 'Asia/Ulaanbaatar',
  'Thailand':                 'Asia/Bangkok',
  'Vietnam':                  'Asia/Ho_Chi_Minh',
  'Cambodia':                 'Asia/Phnom_Penh',
  'Laos':                     'Asia/Vientiane',
  'Myanmar':                  'Asia/Rangoon',
  'Malaysia':                 'Asia/Kuala_Lumpur',
  'Singapore':                'Asia/Singapore',
  'Indonesia':                'Asia/Jakarta',
  'Philippines':              'Asia/Manila',
  'Brunei':                   'Asia/Brunei',
  'Timor-Leste':              'Asia/Dili',

  // Africa
  'South Africa':             'Africa/Johannesburg',
  'Nigeria':                  'Africa/Lagos',
  'Egypt':                    'Africa/Cairo',
  'Morocco':                  'Africa/Casablanca',
  'Algeria':                  'Africa/Algiers',
  'Tunisia':                  'Africa/Tunis',
  'Libya':                    'Africa/Tripoli',
  'Sudan':                    'Africa/Khartoum',
  'Ethiopia':                 'Africa/Addis_Ababa',
  'Kenya':                    'Africa/Nairobi',
  'Tanzania':                 'Africa/Dar_es_Salaam',
  'Uganda':                   'Africa/Kampala',
  'Ghana':                    'Africa/Accra',
  "Côte d'Ivoire":            'Africa/Abidjan',
  'Ivory Coast':              'Africa/Abidjan',
  'Senegal':                  'Africa/Dakar',
  'Cameroon':                 'Africa/Douala',
  'Zimbabwe':                 'Africa/Harare',
  'Zambia':                   'Africa/Lusaka',
  'Mozambique':               'Africa/Maputo',
  'Madagascar':               'Indian/Antananarivo',
  'Mauritius':                'Indian/Mauritius',
  'Rwanda':                   'Africa/Kigali',
  'Angola':                   'Africa/Luanda',
  'Namibia':                  'Africa/Windhoek',
  'Botswana':                 'Africa/Gaborone',

  // Oceania
  'Australia':                'Australia/Sydney',
  'New Zealand':              'Pacific/Auckland',
  'Papua New Guinea':         'Pacific/Port_Moresby',
  'Fiji':                     'Pacific/Fiji',
};
